server.port=8092

spring.application.name=hotelAPI

spring.profiles.active=h2
#spring.profiles.active=mysql
#for mysql connection

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html